apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-project-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-project
  template:
    metadata:
      labels:
        app: the-project
    spec:
      volumes:
        - name: image-cache
          persistentVolumeClaim:
            claimName: shared-pvc
      containers:
        - name: the-project
          image: the_project:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: image-cache
              mountPath: /app/cache